project:
  type: website
  output-dir: docs
  render:
    - website/index.ipynb
    - website/articles.qmd
    - website/nba-scoring.ipynb
    - website/btc-accumulation.ipynb

website:
  title: "data-articles"
  navbar:
    left:
      - href: website/index.ipynb
        text: Home
      - href: website/articles.qmd
        text: Articles

format:
  html:
    theme:
      - cosmo
      - brand
    css: website/styles.css
    toc: true

